package main

import "google.golang.org/protobuf/compiler/protogen"

// generateNew generates a _new.pb.go file containing gRPC service definitions.
func generateNew(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	filename := file.GeneratedFilenamePrefix + "_new.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by https://github.com/smartwalle/protoc-gen-sm. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	for _, message := range file.Messages {
		g.P("func New", message.GoIdent.GoName, "() *", message.GoIdent.GoName, "{")
		g.P("return &", message.GoIdent.GoName, "{}")
		g.P("}")
		g.P()

		//g.P("func (x *", message.GoIdent.GoName, ") Release() {")
		//g.P("}")
		//g.P()
	}
	return g
}
